---
- hosts: masters
  become: true
  become_user: root
  tasks:
    - debug:
        msg: "{{ansible_host}}"
    - name: reset helm
      shell: |
        kubectl -n kube-system delete deployment tiller-deploy
        kubectl delete clusterrolebinding tiller
        kubectl -n kube-system delete serviceaccount tiller
nohup rm /usr/local/bin/linkerd /root/.linkerd2 -rf
      failed_when: false
- hosts: k8s
  become: true
  become_user: root
  tasks:
    - debug:
        msg: "{{ansible_host}}"
    - name: reset kubeadm
      shell: |
        kubectl drain {{ansible_hostname}} --delete-local-data --force --ignore-daemonsets
        kubectl delete node {{ansible_hostname}} 
        kubeadm reset -f && swapoff -a
        rm -rfv /etc/kubernetes /root/.kube /var/etcd
      register: result
      ignore_errors: true
      failed_when: false
    - debug: var=result.stdout_lines    