---
- hosts: masters
  become: true
  become_user: root
  roles:
    # - geerlingguy.docker
    - k8s
    - masters

- hosts: workers
  become: true
  become_user: root
  roles:
    - geerlingguy.docker
    - k8s
    - workers