---
# tasks file for k8s
- name: 'check if docker is installed'
  command: docker version
  ignore_errors: true
  register: check_docker
  changed_when: false

- name: 'Importing geerlingguy.docker role'
  import_role:
    name: geerlingguy.docker
  when: "check_docker is failed"

- name: Prepare centos
  import_tasks: pre-centos.yml
    
- name: Installing kubeadm
  package:
    name: 
      - kubeadm-{{KUBERNETES_VERSION}}
      - kubelet-{{KUBERNETES_VERSION}}
      - kubectl-{{KUBERNETES_VERSION}}
    state: present