---
# tasks file for k8s
- name: 'check if docker is installed'
  command: docker version
  ignore_errors: true
  register: check_docker
  changed_when: false

- name: 'Importing geerlingguy.docker role'
  import_role:
    name: geerlingguy.docker
  when: "check_docker is failed"

- name: Prepare centos
  import_tasks: pre-centos.yml
    
- name: Installing kubeadm
  package:
    name: 
      - kubeadm-{{KUBERNETES_VERSION}}
      - kubelet-{{KUBERNETES_VERSION}}
      - kubectl-{{KUBERNETES_VERSION}}
      - bash-completion
      - vim
    state: present

- name: ensure kubelet env KUBELET_EXTRA_ARGS is set
  lineinfile:
    path: '/etc/sysconfig/kubelet'
    regexp: '^KUBELET_EXTRA_ARGS.*'
    line: 'KUBELET_EXTRA_ARGS="--node-ip={{ ansible_host | default(ansible_default_ipv4.address) }}"'
  register: kubernetes_systemd_register

- debug: var=kubernetes_systemd_register

- name: Reload systemd unit if args were changed.
  systemd:
    daemon_reload: true
  when: kubernetes_systemd_register is changed

- name: Creating kubectl alias
  lineinfile:
    path: /etc/bashrc
    line: "alias kc=kubectl"
    state: present
    insertafter: EOF
    create: yes

- name: Creating kubectl -n kube-system alias
  lineinfile:
    path: /etc/bashrc
    line: "alias kcs='kubectl -n kube-system'"
    state: present
    insertafter: EOF
    create: yes

- name: Creating bash-completion config
  lineinfile:
    path: /root/.bashrc
    state: present
    insertafter: EOF
    create: yes
    line: "source <(kubectl completion bash)"
