---
- name: Install helm
  import_role:
    name: andrewrothstein.kubernetes-helm

- name: Helm symlinking
  file:
    src: /usr/local/bin/helm
    dest: /usr/bin/helm
    state: link

# - name: Check if tiller is configured
#   command: kubectl -n kube-system get pod
#   register: check_tiller
#   changed_when: false

- debug: var=check_tiller

    #helm init --node-selectors k8s_role_devops=devops
    #kubectl -n kube-system create serviceaccount tiller
    #kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
    #helm init --service-account=tiller  --node-selectors k8s_role_devops=devops --upgrade
    
- name: Helm setup
  shell: |
    helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    helm repo update
  #when: " 'tiller' not in check_tiller.stdout"

- name: Checking nginx-ingress
  shell: kubectl get ns ingress-nginx || echo 'not found'
  register: ingress_check

- name: Installing nginx-ingress
  shell: |
    kubectl create ns ingress-nginx
    helm upgrade -i nginx-ingress stable/nginx-ingress --namespace ingress-nginx --set controller.publishService.enabled=true
  when: '"not found" in ingress_check.stdout'
    