---
- name: Checking linkerd
  shell:  /usr/local/bin/linkerd check || echo "Status check results are ×"
  failed_when: False
  register: check_linkerd

- debug: var=check_linkerd

- name: Downloading Linkerd
  shell: |
    curl -sL https://run.linkerd.io/install -o /root/install.sh && chmod +x /root/install.sh
    /root/install.sh
    cp /root/.linkerd2/bin/linkerd /usr/local/bin/
  when:
    - '"not found" in check_linkerd.stderr' 

- name: Configuring Linkerd
  block:
  ###BEGIN

    - name: Ensure /etc/linkerd is created
      file:
        path: "/etc/linkerd/{{item}}"
        state: directory
      with_items: 
        - base
        - overlays/prod
    
    - name: Kustomizing Linkerd - Base
      template: 
        src: linkerd/kustomize_linkerd_base.yml
        dest: /etc/linkerd/base/kustomization.yaml

    - name: Kustomizing Linkerd - Prod
      template: 
        src: linkerd/kustomize_linkerd_prod.yml
        dest: /etc/linkerd/overlays/prod/kustomization.yaml
    
    - name: Kustomizing Linkerd - Patch
      template: 
        src: linkerd/linkerd_deploy_patch.yaml
        dest: /etc/linkerd/overlays/prod/deploy_patch.yaml      

    - name: Deploying Linkerd on K8s
      shell: |
        /usr/local/bin/linkerd install > /etc/linkerd/base/linkerd.yaml
        kubectl apply -k /etc/linkerd/overlays/prod

    - name: Templating linkerd-dash
      template: 
        src: linkerd/linkerd-dashboard.yml
        dest: /etc/linkerd-dashboard.yml
        force: yes

    - name: Exposing dashboard
      shell: kubectl apply -f /etc/linkerd-dashboard.yml

    ###END  
  any_errors_fatal: true
  when: 
    - '"Status check results are ×" in check_linkerd.stdout'
