---
- name: Checking linkerd
  shell:  /usr/local/bin/linkerd check
  failed_when: False
  register: check_linkerd

- debug: var=check_linkerd

- name: Downloading Linkerd
  shell: |
    curl -sL https://run.linkerd.io/install -o /root/install.sh && chmod +x /root/install.sh
    /root/install.sh
    cp /root/.linkerd2/bin/linkerd /usr/local/bin/
  when:
    - '"not found" in check_linkerd.stderr' 

- name: Configuring Linkerd
  block:
  ###BEGIN
    - name: Deploying Linkerd on K8s
      shell: /usr/local/bin/linkerd install | kubectl apply -f -

    - name: Ensure /etc/linkerd is created
      file:
        path: /etc/linkerd
        state: directory

    - name: Templating linkerd-dash
      template: 
        src: linkerd-dashboard.yml
        dest: /etc/linkerd-dashboard.yml
        force: yes

    - name: Exposing dashboard
      shell: kubectl apply -f /etc/linkerd-dashboard.yml

    ###END  
  any_errors_fatal: true
  # when: 
  #   - '"Status check results are ×" in check_linkerd.stdout'
