---
# tasks file for masters

- name: Check if kubernetes is configured properly
  delegate_to: "{{ groups.masters[0] }}"
  command:
    kubectl cluster-info
  register: cluster_info
  changed_when: "'is running at' not in cluster_info.stdout"
  ignore_errors: true

- name: Install master
  include: install.yml
  when: cluster_info is failed

- name: include master ha tasks
  include: ha.yml
  when: ( groups.masters | length > 1 ) and inventory_hostname != groups.masters[0]

- name: Include helm task
  include: helm.yml


