---
# tasks file for masters

- name: Check if kubernetes is configured properly
  delegate_to: "{{ groups.masters[0] }}"
  command:
    kubectl cluster-info
  register: cluster_info
  changed_when: "'is running at' not in cluster_info.stdout"
  ignore_errors: true

- name: Install master
  include: install.yml
  when: cluster_info is failed

- name: include master ha tasks
  include: ha.yml
  when: ( groups.masters | length > 1 ) and inventory_hostname != groups.masters[0]

- name: Include helm task
  include: helm.yml

- name: Getting labels
  delegate_to: "{{groups.masters[0]}}"
  shell: "kubectl get nodes {{ansible_hostname}} --show-labels"
  register: get_labels
  changed_when: false

- debug: msg="{{(get_labels.stdout_lines |join(' '))}}"

- name: Including labels
  delegate_to: "{{groups.masters[0]}}"
  shell: kubectl label nodes {{ansible_hostname}} k8s_role_{{item}}={{item}}
  with_items: "{{k8s_roles}}"
  when: 
    - (get_labels.stdout_lines |join(' ')) is not match('.*?k8s_role_.*?')
  register: include_labels


