---
- name: "Check if Flannel network plugin is installed"
  shell: 
    kubectl -n kube-system get pod
  register: check_network
  changed_when: "'flannel' not in check_network.stdout"
  
- name: "Deploy Flannel CNI"
  shell:
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml
