apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      certSANs:
      - k8s.sistemafieg.org.br
      - fieg-kube-master-01
      - fieg-kube-master-01
      - 10.21.154.99
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta1
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: ""
    controllerManager: {}
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.13.3
    networking:
      dnsDomain: cluster.local
      podSubnet: ""
      serviceSubnet: 10.96.0.0/12
    scheduler: {}
  ClusterStatus: |
    apiEndpoints:
      fieg-kube-master-01:
        advertiseAddress: 10.21.154.99
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta1
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2019-02-12T10:49:27Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "177"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
  uid: de7be23d-2eb3-11e9-980d-005056823e8c

  