apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-11T10:56:26Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "221"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 51537120-43ec-11e9-b040-525400f0e95b
