---
# tasks file for workers
- name: check node is already in cluster
  # delegate_to: "{{ groups.masters[0] }}"
  command: "kubectl get nodes -n kube-system -o name"
  register: node_registry
  changed_when: false
  ignore_errors: true

- debug: var=node_registry.stdout
- debug: msg="node/{{ansible_nodename}}"

- name: Get join command from master
  delegate_to: "{{ groups.masters[0] }}"
  command: "kubeadm token create --print-join-command"
  register: join_token

- debug: var=join_token.stdout

- name: Join workers into cluster
  command: "{{join_token.stdout}}"
  when: ( 'node/' + ansible_nodename ) not in node_registry.stdout_lines
  register: join_output

- debug: var=join_output.stoutlines
